# Site settings
title:          Yitong's Blog
baseurl:        ""
url:            "https://yitong0768.cc"

# Author
author:
  name:         Yitong Huang
  url:          https://yitong0768.cc
  email:        yitong0768@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
