# Site settings
title:          Yitong's Blog
baseurl:        ""
url:            "https://blog.huangyt.tech"

# Author
author:
  name:         Yitong Huang
  url:          http://blog.huangyt.tech
  email:        yitong0768@gmail.com

# Build settings
markdown:       kramdown
excerpt_separator: <!--more-->
# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
